trigger:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial (4c2d736a-24d5-44d1-9d9e-916c8f596826)'
    appType: 'webApp'
    WebAppName: 'HYD-APP'
    packageForLinux: '$(System.DefaultWorkingDirectory)'
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: THIS IS MY FIRST PIPE LINE GUYS--!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PublishBuildArtifacts@1
